### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by mancharagopan** [HASecuritySolutions/VulnWhisperer#136]
When i executed  `sudo vuln_whisperer -c configs/frameworks_example.ini -s openvas` i am getting an error
```
@vulnwisper:~/VulnWhisperer-master$ vuln_whisperer -c configs/frameworks_example.ini -s
Traceback (most recent call last):
  File "/usr/local/bin/vuln_whisperer", line 4, in <module>
    __import__('pkg_resources').run_script('VulnWhisperer==1.7.1', 'vuln_whisperer')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1438, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/VulnWhisperer-1.7.1-py2.7.egg/EGG-INFO/scripts/vuln_whisperer", line 6, in <module>
    from vulnwhisp.vulnwhisp import vulnWhisperer
  File "/usr/local/lib/python2.7/dist-packages/VulnWhisperer-1.7.1-py2.7.egg/vulnwhisp/vulnwhisp.py", line 6, in <module>
    from frameworks.nessus import NessusAPI
  File "/usr/local/lib/python2.7/dist-packages/VulnWhisperer-1.7.1-py2.7.egg/vulnwhisp/frameworks/nessus.py", line 1, in <module>
    import requests
ImportError: No module named requests
```

**Comment by mancharagopan** [comment]
I installed all the missing packages

**Comment by xxoc77** [comment]
I have the same issue, which packages were you missing?

**Comment by mancharagopan** [comment]
> 
> 
> I have the same issue, which packages were you missing?

What is the error message you receive?

**Comment by xxoc77** [comment]
> > I have the same issue, which packages were you missing?
> 
> What is the error message you receive?

Traceback (most recent call last):
  File "/usr/local/bin/vuln_whisperer", line 4, in <module>
    __import__('pkg_resources').run_script('VulnWhisperer==1.7.1', 'vuln_whisperer')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1438, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/VulnWhisperer-1.7.1-py2.7.egg/EGG-INFO/scripts/vuln_whisperer", line 6, in <module>
    from vulnwhisp.vulnwhisp import vulnWhisperer
  File "/usr/local/lib/python2.7/dist-packages/VulnWhisperer-1.7.1-py2.7.egg/vulnwhisp/vulnwhisp.py", line 6, in <module>
    from frameworks.nessus import NessusAPI
  File "/usr/local/lib/python2.7/dist-packages/VulnWhisperer-1.7.1-py2.7.egg/vulnwhisp/frameworks/nessus.py", line 1, in <module>
    import requests
ImportError: No module named requests

**Comment by mancharagopan** [comment]
> 
> 
> > > I have the same issue, which packages were you missing?
> > 
> > 
> > What is the error message you receive?
> 
> Traceback (most recent call last):
> File "/usr/local/bin/vuln_whisperer", line 4, in
> **import**('pkg_resources').run_script('VulnWhisperer==1.7.1', 'vuln_whisperer')
> File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 658, in run_script
> self.require(requires)[0].run_script(script_name, ns)
> File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 1438, in run_script
> exec(code, namespace, namespace)
> File "/usr/local/lib/python2.7/dist-packages/VulnWhisperer-1.7.1-py2.7.egg/EGG-INFO/scripts/vuln_whisperer", line 6, in
> from vulnwhisp.vulnwhisp import vulnWhisperer
> File "/usr/local/lib/python2.7/dist-packages/VulnWhisperer-1.7.1-py2.7.egg/vulnwhisp/vulnwhisp.py", line 6, in
> from frameworks.nessus import NessusAPI
> File "/usr/local/lib/python2.7/dist-packages/VulnWhisperer-1.7.1-py2.7.egg/vulnwhisp/frameworks/nessus.py", line 1, in
> import requests
> ImportError: No module named requests

run` pip install requests`

**Comment by mancharagopan** [comment]
And do the same to all the packages that mentioned in ImportError: No module named **requests**

**Comment by xxoc77** [comment]
> And do the same to all the packages that mentioned in ImportError: No module named **requests**

I'll try that thanks for the help. I'll let you know if it works!

**Comment by xxoc77** [comment]
Thanks, it worked fine after install of dependencies

**Comment by reactor7171** [comment]
this is weird... those packages should have been installed when doing the `pip install -r /path/to/VulnWhisperer/requirements.txt`, did something fail in the deployment process?
