### ISSUE TITLE
ImportError: No module named 'base'

### ISSUE THREAD

**Issue by tompenning** [HASecuritySolutions/VulnWhisperer#185]
When I run VulnWhisper I get the following error ImportError: No module named 'base'

Here are the steps I went through, appreciate any help.

[root@dev-8 opt]# python3 -m venv /opt/VulnWhisperer/venv
[root@dev-8 opt]# chmod 777 /opt/VulnWhisperer
# copied extracted ZIP files to /opt/VulnWhisperer/. from localhost, which were downloaded from https://github.com/HASecuritySolutions/VulnWhisperer
[root@dev-8 opt]# chmod 755 /opt/VulnWhisperer
[root@dev-8 VulnWhisperer]# source venv/bin/activate
(venv) [root@dev-8 VulnWhisperer]# pip install -r requirements.txt
(venv) [root@dev-8 VulnWhisperer]# python setup.py install

(venv) [root@dev-8 VulnWhisperer]# vuln_whisperer -F -c configs/tenable.ini -s tenable
Traceback (most recent call last):
  File "/opt/VulnWhisperer/venv/bin/vuln_whisperer", line 4, in <module>
    __import__('pkg_resources').run_script('VulnWhisperer==1.8', 'vuln_whisperer')
  File "/opt/VulnWhisperer/venv/lib64/python3.4/site-packages/pkg_resources/__init__.py", line 661, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/VulnWhisperer/venv/lib64/python3.4/site-packages/pkg_resources/__init__.py", line 1441, in run_script
    exec(code, namespace, namespace)
  File "/opt/VulnWhisperer/venv/lib/python3.4/site-packages/VulnWhisperer-1.8-py3.4.egg/EGG-INFO/scripts/vuln_whisperer", line 6, in <module>
    from vulnwhisp.vulnwhisp import vulnWhisperer
  File "/opt/VulnWhisperer/venv/lib64/python3.4/site-packages/VulnWhisperer-1.8-py3.4.egg/vulnwhisp/vulnwhisp.py", line 5, in <module>
    from base.config import vwConfig
ImportError: No module named 'base'

(venv) [root@dev-8 VulnWhisperer]# pip install base
DEPRECATION: Python 3.4 support has been deprecated. pip 19.1 will be the last one supporting it. Please upgrade your Python as Python 3.4 won't be maintained after March 2019 (cf PEP 429).
Collecting base
  Downloading https://files.pythonhosted.org/packages/1b/e5/464fcdb2cdbafc65f0b2da261dda861fa51d80e1a4985a2bb00ced080549/base-1.0.4.tar.gz
Installing collected packages: base
  Running setup.py install for base ... done
Successfully installed base-1.0.4

(venv) [root@dev-8 VulnWhisperer]# vuln_whisperer -F -c configs/tenable.ini -s tenable
Traceback (most recent call last):
  File "/opt/VulnWhisperer/venv/bin/vuln_whisperer", line 4, in <module>
    __import__('pkg_resources').run_script('VulnWhisperer==1.8', 'vuln_whisperer')
  File "/opt/VulnWhisperer/venv/lib64/python3.4/site-packages/pkg_resources/__init__.py", line 661, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/VulnWhisperer/venv/lib64/python3.4/site-packages/pkg_resources/__init__.py", line 1441, in run_script
    exec(code, namespace, namespace)
  File "/opt/VulnWhisperer/venv/lib/python3.4/site-packages/VulnWhisperer-1.8-py3.4.egg/EGG-INFO/scripts/vuln_whisperer", line 6, in <module>
    from vulnwhisp.vulnwhisp import vulnWhisperer
  File "/opt/VulnWhisperer/venv/lib64/python3.4/site-packages/VulnWhisperer-1.8-py3.4.egg/vulnwhisp/vulnwhisp.py", line 5, in <module>
    from base.config import vwConfig
ImportError: No module named 'base.config'

pip install base.config

DEPRECATION: Python 3.4 support has been deprecated. pip 19.1 will be the last one supporting it. Please upgrade your Python as Python 3.4 won't be maintained after March 2019 (cf PEP 429).
Collecting base.config
  ERROR: Could not find a version that satisfies the requirement base.config (from versions: none)
ERROR: No matching distribution found for base.config

**Comment by reactor7171** [comment]
Hi @tompenning,
I believe the issue here is that you are running VulnWhisperer in a Python 3 virtualenv instead of a Python 2.7 one, could you try again with 2.7 and see if it still breaks?
Cheers!

**Comment by jsposato** [comment]
is there a plan to support Python3 with version 2 going EOL on Jan 1?

**Comment by reactor7171** [comment]
Hi @jsposato,
For that topic there is already another issue opened, #197, I will reply over there.
Cheers!
