### ISSUE TITLE
[ELK6] Openvas logstash Error

### ISSUE THREAD

**Issue by kingmario7** [HASecuritySolutions/VulnWhisperer#76]
I didn't view an issue for that, I don't know if i did something wrong but : 

I tried to install vulnwhisperer on debian 9 : 

1) Installed ELK
2) Cloned the vuln_whisperer repository and followed the installed requirements
3) I created a new pipeline in logstash and setup the 3000_openvas.conf
4) I created an openvas.ini configuration file. 
5) Launched vulnwhisperer correctly with the configuration file. 

The vulnwhisperer binary executed well and the reports in json are in /opt/vulnwhisperer/openvas

> 
[2018-07-05T10:24:02,280][ERROR][logstash.pipeline        ] Exception in pipelineworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash. {:pipeline_id=>"04-vulnwhisperer", "exception"=>"undefined method `tr' for 4.3:Float", "backtrace"=>["/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-filter-mutate-3.3.1/lib/logstash/filters/mutate.rb:344:in `convert_float'", "org/jruby/RubyMethod.java:115:in `call'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-filter-mutate-3.3.1/lib/logstash/filters/mutate.rb:313:in `block in convert'", "org/jruby/RubyHash.java:1343:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-filter-mutate-3.3.1/lib/logstash/filters/mutate.rb:299:in `convert'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-filter-mutate-3.3.1/lib/logstash/filters/mutate.rb:252:in `filter'", "/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:145:in `do_filter'", "/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:164:in `block in multi_filter'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:161:in `multi_filter'", "/usr/share/logstash/logstash-core/lib/logstash/filter_delegator.rb:44:in `multi_filter'", "(eval):4734:in `block in initialize'", "org/jruby/RubyArray.java:1734:in `each'", "(eval):4717:in `block in initialize'", "(eval):1201:in `block in filter_func'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:443:in `filter_batch'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:422:in `worker_loop'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:384:in `block in start_workers'"], :thread=>"#<Thread:0x74d20d19 sleep>"}

Did I do something wrong ?

**Comment by austin-taylor** [comment]
Which version of logstash?

**Comment by austin-taylor** [comment]
We currently only support version 5,x of ELK. Shouldn't be too much work to upgrade to 6.x

**Comment by kingmario7** [comment]
Yes, I'm with ELK 6.x thank you. I didn't see that it was compatible just avec 5.x version

**Comment by austin-taylor** [comment]
If you get it covered to 6.x, please submit a PR with your visualizations and we will include it.  Thank you!

**Comment by reactor7171** [comment]
Will close both #76 and #34 in pro of #86 in order to unify issues that are related to the same.
